"use client";

import { useMemo, useRef, useState } from "react";
import { Check, Clipboard } from "lucide-react";

const clamp = (value: number, min = 0, max = 100) => Math.min(max, Math.max(min, value));
function hslToHex(h: number, s: number, l: number) { s /= 100; l /= 100; const c = (1 - Math.abs(2 * l - 1)) * s, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), m = l - c / 2; const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x]; return `#${[r, g, b].map((v) => Math.round((v + m) * 255).toString(16).padStart(2, "0")).join("")}`.toUpperCase(); }
function hexToRgb(hex: string) { const value = parseInt(hex.slice(1), 16); return [(value >> 16) & 255, (value >> 8) & 255, value & 255]; }
function hexToHsl(hex: string) { const [r, g, b] = hexToRgb(hex).map((v) => v / 255); const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2, d = max - min; let h = 0; if (d) h = max === r ? 60 * (((g - b) / d) % 6) : max === g ? 60 * ((b - r) / d + 2) : 60 * ((r - g) / d + 4); return [Math.round((h + 360) % 360), Math.round(d ? d / (1 - Math.abs(2 * l - 1)) * 100 : 0), Math.round(l * 100)]; }
export function ColorWheel() {
  const [hue, setHue] = useState(258), [saturation, setSaturation] = useState(62), [lightness, setLightness] = useState(60), [mode, setMode] = useState("complementary"), [copied, setCopied] = useState(""); const wheel = useRef<HTMLDivElement>(null);
  const hex = hslToHex(hue, saturation, lightness), rgb = hexToRgb(hex);
  const colors = useMemo(() => { const offsets = mode === "complementary" ? [0, 180] : mode === "analogous" ? [-30, 0, 30] : mode === "triadic" ? [0, 120, 240] : [0, 0, 0, 0, 0]; return offsets.map((offset, i) => mode === "monochromatic" ? hslToHex(hue, saturation, clamp(22 + i * 14)) : hslToHex((hue + offset + 360) % 360, saturation, lightness)); }, [hue, saturation, lightness, mode]);
  function choose(event: React.MouseEvent) { if (!wheel.current) return; const box = wheel.current.getBoundingClientRect(), x = event.clientX - box.left - box.width / 2, y = event.clientY - box.top - box.height / 2; setHue(Math.round((Math.atan2(y, x) * 180 / Math.PI + 450) % 360)); setSaturation(clamp(Math.round(Math.hypot(x, y) / (box.width / 2) * 100))); }
  async function copy(value: string) { await navigator.clipboard.writeText(value); setCopied(value); setTimeout(() => setCopied(""), 1200); }
  function changeHex(value: string) { if (!/^#[0-9a-f]{6}$/i.test(value)) return; const [h, s, l] = hexToHsl(value); setHue(h); setSaturation(s); setLightness(l); }
  return <div className="color-tool"><div className="color-picker"><div ref={wheel} className="color-wheel" onClick={choose} role="slider" aria-label="Color hue and saturation wheel" aria-valuenow={hue}><span style={{ transform: `rotate(${hue - 90}deg) translateX(${saturation * 1.08}px)` }} /></div><label className="lightness">Lightness<input type="range" min="5" max="95" value={lightness} onChange={(e) => setLightness(+e.target.value)} /></label></div><div className="color-controls"><div className="color-preview" style={{ backgroundColor: hex }} /><div className="color-values"><label>HEX<input value={hex} maxLength={7} onChange={(e) => changeHex(e.target.value)} /></label><label>RGB<input readOnly value={`${rgb[0]}, ${rgb[1]}, ${rgb[2]}`} /></label><label>HSL<input readOnly value={`${hue}°, ${saturation}%, ${lightness}%`} /></label></div><button className="button secondary" onClick={() => copy(hex)}>{copied === hex ? <Check size={17} /> : <Clipboard size={17} />}Copy {hex}</button></div><section className="palette-panel"><div><h3>Generated palette</h3><select value={mode} onChange={(e) => setMode(e.target.value)}><option value="complementary">Complementary</option><option value="analogous">Analogous</option><option value="triadic">Triadic</option><option value="monochromatic">Monochromatic</option></select></div><div className="palette">{colors.map((color, i) => <button key={`${color}-${i}`} style={{ background: color, color: parseInt(color.slice(1), 16) > 0x999999 ? "#171525" : "#fff" }} onClick={() => copy(color)}><span>{copied === color ? "Copied" : color}</span></button>)}</div></section></div>;
}
