import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { NextResponse } from "next/server";
import { z } from "zod";

export const runtime = "nodejs";
const bodySchema = z.object({ url: z.string().url().max(2048) });
const privateIp = /^(127\.|10\.|0\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|::1$|fc|fd|fe80)/i;

async function validateTarget(input: string) { const url = new URL(input); if (!["http:", "https:"].includes(url.protocol) || url.username || url.password) throw new Error("Only public HTTP or HTTPS URLs are supported."); const records = await lookup(url.hostname, { all: true }); if (!records.length || records.some(({ address }) => privateIp.test(address) || (isIP(address) === 0))) throw new Error("Private or unresolved network addresses are not allowed."); return url; }
function readableText(html: string) { return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ").replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&(?:nbsp|amp|quot|apos|lt|gt);/g, " ").replace(/&#\d+;/g, " ").replace(/\s+/g, " ").trim(); }
export async function POST(request: Request) { try { const { url: input } = bodySchema.parse(await request.json()); const target = await validateTarget(input); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); const response = await fetch(target, { signal: controller.signal, redirect: "manual", headers: { "User-Agent": "FigimiWordCounter/1.0 (+public page analysis)", Accept: "text/html" } }); clearTimeout(timeout); if (response.status >= 300 && response.status < 400) throw new Error("Redirecting URLs are not analyzed for security. Paste the final page URL instead."); if (!response.ok) throw new Error(`The page returned HTTP ${response.status}.`); const type = response.headers.get("content-type") || ""; if (!type.includes("text/html")) throw new Error("The URL does not point to an HTML page."); const length = Number(response.headers.get("content-length") || 0); if (length > 2_000_000) throw new Error("This page is too large to analyze."); const html = (await response.text()).slice(0, 2_000_000), text = readableText(html); const words = text.match(/[\p{L}\p{N}'’-]+/gu) || []; const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g, " ").trim() || ""; return NextResponse.json({ url: target.toString(), title, words: words.length, characters: text.length, readingTime: words.length ? Math.ceil(words.length / 200) : 0 }); } catch (error) { const message = error instanceof z.ZodError ? "Enter a valid public URL." : error instanceof Error ? error.message : "Unable to analyze this page."; return NextResponse.json({ error: message }, { status: 400 }); } }
