import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { AdSlot } from "@/components/ad-slot";
import { BlogCard } from "@/components/blog-card";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { getPostBySlug, getPublishedPosts, getRelatedPosts } from "@/lib/data";
import { absoluteUrl, siteConfig } from "@/lib/site";

export const revalidate = 300;
export async function generateStaticParams() { return (await getPublishedPosts()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const post = await getPostBySlug((await params).slug); if (!post) return {}; const title = post.seo_title || post.title, image = post.og_image || post.featured_image || undefined; return { title, description: post.meta_description, authors: [{ name: post.author }], alternates: { canonical: `/blog/${post.slug}` }, openGraph: { type: "article", url: `/blog/${post.slug}`, title, description: post.meta_description, publishedTime: post.published_at || undefined, modifiedTime: post.updated_at, authors: [post.author], tags: post.tags, images: image ? [{ url: image, alt: post.featured_image_alt }] : undefined }, twitter: { card: "summary_large_image", title, description: post.meta_description, images: image ? [image] : undefined } }; }
export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) { const post = await getPostBySlug((await params).slug); if (!post) notFound(); const related = await getRelatedPosts(post), date = post.published_at ? new Intl.DateTimeFormat("en", { dateStyle: "long" }).format(new Date(post.published_at)) : ""; const schema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.meta_description, image: post.featured_image ? [post.featured_image] : undefined, datePublished: post.published_at, dateModified: post.updated_at, author: { "@type": "Person", name: post.author }, publisher: { "@type": "Organization", name: siteConfig.name, url: siteConfig.url }, mainEntityOfPage: absoluteUrl(`/blog/${post.slug}`), keywords: post.tags.join(", ") };
return <><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Blog", href: "/blog" }, { label: post.title }]} /><article className="post"><header><span className="post-category">{post.category}</span><h1>{post.title}</h1><p>{post.meta_description}</p><div className="post-byline"><span>By {post.author}</span><time dateTime={post.published_at || undefined}>{date}</time></div></header>{post.featured_image && <Image className="post-featured" src={post.featured_image} alt={post.featured_image_alt || post.title} width={1200} height={675} sizes="(max-width: 860px) 100vw, 820px" priority />}<AdSlot placement="post-content-top" /><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{post.body}</ReactMarkdown></div><AdSlot placement="post-content-bottom" /></article>{related.length > 0 && <section className="related"><h2>Related posts</h2><div className="blog-grid">{related.map((item) => <BlogCard key={item.id} post={item} />)}</div></section>}</div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /></>; }
